export const GAME_CONFIG = Object.freeze({
  worldWidth: 1600,
  worldHeight: 900,
  fixedStepSeconds: 1 / 60,
  maxSubsteps: 8,
  teamSize: 3,
  startingHealth: 100,
  humanTurnSeconds: 35,
  grenadeFuseSeconds: 3,
  alienRadius: 18,
  walkSpeedPixelsPerSecond: 90,
  jumpVelocityPixelsPerSecond: -260,
  gravityPixelsPerSecondSquared: 420,
  windMinPixelsPerSecondSquared: -40,
  windMaxPixelsPerSecondSquared: 40,
  bazookaMinSpeedPixelsPerSecond: 220,
  bazookaMaxSpeedPixelsPerSecond: 620,
  grenadeRestitution: 0.55,
  grenadeWindFactor: 0.35,
  explosionRadius: 54,
  maxDamage: 60,
  dynamicTimeoutSeconds: 8,
  minZoom: 0.65,
  maxZoom: 2,
  aiMaxSimulations: 240,
  aiMaxMilliseconds: 250,
});
